---
- name: validate required variable is set
  fail:
    msg: "missing required fact: config_file"
  when: eos_config_file is undefined

- name: display message
  debug:
    msg: "eos configuration rollback is {{ eos_rollback_enabled | ternary('enabled', 'disabled') }}"

- name: check if device supports configure sessions
  block:
    - name: display configuration session name (if configured)
      debug:
        msg: "eos configure session name is {{ eos_config_session_name }}"

    - name: check if device supports config sessions
      cli:
        command: "show configuration sessions"
      register: eos_supports_sessions
      ignore_errors: true

    - name: fail host if replace requested and not supported
      fail:
        msg: config replace is not supported on this version of eos
      when: eos_supports_sessions is failed
  when: eos_config_replace

- name: checkpoint existing active configuration for rollback
  block:
    - name: create configuration checkpoint
      cli:
        command: "copy running-config flash:{{ eos_config_checkpoint_filename }}"
      register: eos_checkpoint_command

    - name: verify configuration checkpoint was successful
      fail:
        msg: "error attemping to create configuration checkpoint"
      when: eos_checkpoint_command.stdout != 'Copy completed successfully.'
  when: eos_rollback_enabled

- name: load configuration onto target device
  block:
    - name: perform configuration replace on device
      include_tasks: includes/config_replace.yaml
      when: eos_config_replace

    - name: perform configuration merge on device
      include_tasks: includes/config_merge.yaml
      when: not eos_config_replace
  rescue:
    - name: display message
      debug:
        msg: "error configuration device, starting rollback"

    - name: configuration rollback pre hook
      include_tasks: "{{ eos_configuration_rollback_pre_hook }}"
      when: eos_configuration_rollback_pre_hook is defined and eos_rollback_enabled

    - name: rollback configuration
      cli:
        command: "configure replace flash:{{ eos_config_checkpoint_filename }}"
      when: eos_rollback_enabled

    - name: remove configuration checkpoint file
      cli:
        command: "delete flash:{{ eos_config_checkpoint_filename }}"
      when: eos_rollback_enabled

    - name: configuration rollback post hook
      include_tasks: "{{ eos_configuration_rollback_post_hook }}"
      when: eos_configuration_rollback_post_hook is defined and eos_rollback_enabled

    - name: display message
      debug:
        msg: "successfully completed configuration rollback"
      when: eos_rollback_enabled

    - name: fail host due to config load error
      fail:
        msg: "error loading configuration onto target device"

- name: remove configuration checkpoint file
  cli:
    command: "delete flash:{{ eos_config_checkpoint_filename }}"
  when: eos_rollback_enabled

