---
- name: load configuration onto target device
  block:
    - name: create new configuration session
      cli:
        command: "configure session {{ eos_config_session_name }}"

    - name: apply configuration statements
      cli:
        command: "{{ item.strip() }}"
      loop: "{{ lookup('network_template', eos_config_file) }}"
      when: item != 'end'

    - name: get configuration diff
      cli:
        command: "show session-config diffs"
      register: eos_config_diff
      changed_when: eos_config_diff.stdout

    - name: display config diff
      debug:
        msg: "{{ eos_config_diff.stdout.splitlines() }}"

    - name: commit the configuration and exit
      cli:
        command: commit

    - name: remove configuration session
      cli:
        command: "no configure session {{ eos_config_session_name }}"
      when: eos_clear_config_session

  rescue:
    - name: abort configuration
      cli:
        command: abort

    - name: mark the host as failed
      fail:
        msg: "error loading configuration onto target device"




